### ISSUE TITLE
Plugin does not respect disableFix configuration

### ISSUE THREAD

**Issue by jor-row** [a-tokyo/stylelint-rem-over-px#5]
**Describe the bug**
See https://stylelint.io/user-guide/configure/#disablefix

With disableFix configuration the plugin still automatically fixes all issues.

**Expected behavior**
If disableFix is true then plugin should warn/error (also based on configuration!) but do nothing.

**Comment by a-tokyo** [comment]
Thanks for reporting

Here's the fix, releasing now.
https://github.com/a-tokyo/stylelint-rem-over-px/pull/6
